### PR TITLE
Add nontech bio

### PR DESCRIPTION
**Pull request by gonuke**
Added a slightly less technical bio as an option (and some minor other formatting/configuration changes)

### CODE REVIEW

**Review by connoramoreno — COMMENTED** [review]
Looks good to me! Is it ready to merge?

**Comment by gonuke** [comment]
I resolved the `Gemfile` inconsistency.

**Comment by MicahGale** [comment]
Is there anything else needed prior to deploying this PR?

**Comment by gonuke** [comment]
I don't think so - since we don't merge our own PR's I'm waiting for someone else to merge this if/when they think it is ready. I think it is...

**Pull request merged**
