### PR TITLE
Updates to personnel pictures and personal page info

### PR DESCRIPTION
**Pull request by pshriwise**
Updating profile picture and links on personal page.

### CODE REVIEW

**Comment by bam241** [comment]
shall we PR against your branch so everything get merged in the same time ?

**Comment by pshriwise** [comment]
@bam241 sure! I have some other small changes in here to my page, but I'm happy to add them all to this PR as well. Thinking about adding a bitmoji to my page instead of my profile picture as wel...

**Comment by kkiesling** [comment]
Just sent a PR to @pshriwise 's branch so that it can get merged as one

**Comment by kkiesling** [comment]
bitmoji

**Comment by gonuke** [comment]
I think there are already twitter, github and bitbucket logos in that directory - we should converge on a common set?

**Comment by pshriwise** [comment]
@gonuke that sounds good. The question is which set I suppose...

I added the github/twitter logos because the pre-existing versions seemed to be a little older.

**Comment by pshriwise** [comment]
- [ ] add target link to respective personal pages for all pics on the main `people` page

**Comment by pshriwise** [comment]
This lost a lot of momentum... closing for now.

**Pull request closed without merging**
