### PR TITLE
Add myself to the CNERG website

### PR DESCRIPTION
**Pull request by biegelk**
It's certainly about time......

Changes to cnerg.github.com/source/people/:
* added `biegel.rst`
* added `biegel.jpg`
* updated `main.rst` to point to biegel.jpg instead of placeholder image

### CODE REVIEW

**Comment by gonuke** [comment]
Perfect timing... as we get ready to switch to a new site :) but mostly with the same data...

**Comment by gonuke** [comment]
You also need to add a link on about line 41 of `main.rst` to link to your page.

**Comment by biegelk** [comment]
Thanks @gonuke, I've added a link to main.rst and it seems to be working.

**Comment by bam241** [comment]
LGTM!
I'll let @gonuke merge I am not sure what are the plan for the new website release...

**Pull request closed without merging**
