### PR TITLE
Adding Owen Selles

### PR DESCRIPTION
**Pull request by oaselles**
Adding myself (a bio, picture, and link from main.html) to the source branch. Let me know if there is a problem!

### CODE REVIEW

**Comment by Baaaaam** [comment]
There is 2 temporary files that you don't want to PR (*~)

**Comment by oaselles** [comment]
Are those the two files?

**Comment by Baaaaam** [comment]
Yes! :) I try to compile it later, and merge it if it is good :)

**Comment by oaselles** [comment]
Great thanks!

**Pull request merged**
