### PR TITLE
created CVT project page and added Cyclus font formatting

### PR DESCRIPTION
**Pull request by mbmcgarry**
Some eye candy for Cyclus and CVT.

### CODE REVIEW

**Comment by opotowsky** [comment]
@mbmcgarry I get this when I `make gh-preview`:
```
checking consistency... /home/opotowsky/cnerg.github.com/source/projects/cvt.rst:: WARNING: document isn't included in any toctree
```

But (1) it does work and (2) I tried changing the format to how the other pages are linked and it didn't work properly. Thoughts?

**Comment by mbmcgarry** [comment]
Yes, I saw the same warning and the same problem trying to fix it. I'm hoping someone can let me know if it's an acceptable warning or how to fix it.


Sent from my Verizon Wireless 4G LTE smartphone


-------- Original message --------
From: opotowsky
Date:05/28/2015 1:49 PM (GMT-08:00)
To: "CNERG/cnerg.github.com"
Cc: Meghan McGarry
Subject: Re: [cnerg.github.com] created CVT project page and added Cyclus font formatting (#44)


@mbmcgarry<https://github.com/mbmcgarry> I get this when I make gh-preview:

checking consistency... /home/opotowsky/cnerg.github.com/source/projects/cvt.rst:: WARNING: document isn't included in any toctree


But (1) it does work and (2) I tried changing the format to how the other pages are linked and it didn't work properly. Thoughts?

-

**Comment by gidden** [comment]
Hi @mbmcgarry ,

A few quick points:
  - I don't see where the link to `<cvt.html>_` is defined
  - if that is meant to be a link to the rendered `cvt.rst`, then it should likely be an [internal link](http://sphinx-doc.org/markup/inline.html#ref-role)

**Comment by mbmcgarry** [comment]
Ping. I got rid of the toctree error and (hopefully) properly linked the cvt description page.

**Comment by gonuke** [comment]
Thanks @mbmcgarry

**Pull request merged**
