### PR TITLE
Adding Stomps Profile

### PR DESCRIPTION
**Pull request by stompsjo**
The [How-To Doc on adding yourself to the website](https://docs.google.com/document/d/1s8DR-TDpMsZ3Sl_vQJZDEtbrFVOfium1BRJlWVjeRig/edit#) says to make a PR with the "develop" branch on the main repo. I don't see a develop branch so I am requesting a pull with the source branch. If that is correct I can update the doc.

### CODE REVIEW

**Comment by bam241** [comment]
@stompsjo I believe this is correct :)

**Comment by bam241** [comment]
LGTM!

**Comment by bam241** [comment]
@stompsjo could you issue an other PR to fix the doc ?

**Comment by stompsjo** [comment]
The README doc on the repo is correct, it's the How-To Google doc that was shared to me that needs the change. I edited it, is a new PR necessary then?

**Comment by bam241** [comment]
No PR required in the googledoc! 

Thank you for catching and fixing this !

**Pull request merged**
