### PR TITLE
Recreate adds for post-doc(s)

### PR DESCRIPTION
**Pull request by gonuke**
Update advertising for new post-doc and/or student

### CODE REVIEW

**Comment by bam241** [comment]
@gonuke is this still up-to-date ?

Sorry it took me so long to come here !

**Comment by gonuke** [comment]
I probably need to revise it again

**Comment by gonuke** [comment]
I think this is ready now @bam241

**Comment by bam241** [comment]
LGTM! Merging1

**Comment by bam241** [comment]
The update has been published :)

**Pull request merged**
