### PR TITLE
Update copyright year in footer.html

### LINKED ISSUE #222: Rev Copyright statement
The copyright statement is currently through 2021. 2023 can definitely be added. It’s unclear if 2022 can be added as well though.

### PR DESCRIPTION
**Pull request by gonuke**
Fixes #222

### CODE REVIEW

**Comment by MicahGale** [comment]
My concern is that the copyright can only be asserted for every year that changes were made to the website. 

So first case: imagine that the website gets abandoned for five years. I think this change should handle that situation as the footer will only be generated when CD is ran, which presumably will only occur when an edit is changed. This should guard against the copyright automatically ratcheting to a new year just because it was visited on Jan 1.

The second case is if a whole year is missed breaking the year range. I think this case is rather unlikely. Either the site will be maintained or it will be abandoned, I don’t think it’s likely for edits to only happen every other year.

**Comment by MicahGale** [comment]
Also if there were really a court case around this the git log would likely be the primary evidence; not the copyright footer.

**Comment by gonuke** [comment]
The website has a weekly update based on our Zotero data, so I think there is at least a weekly timestamp in the git log.    Are you recommending a manual change to this, then?  Or just remove it?  My only reason for caring about what year it says is so that it doesn't look abandoned.  We could replace it with a "Last update: %date%" line instead.

**Comment by MicahGale** [comment]
If it's getting updated weekly with new content I think that should count. 

I'm happy with this as is, once I can test that it builds properly.

**Comment by gonuke** [comment]
Does the docker image work for you?

**Comment by MicahGale** [comment]
Docker is having issues installing github-pages, but vanilla ruby got the job done.

**Review by MicahGale — APPROVED** [review]
Very straight forward. Works for my system.

**Pull request merged**
