### PR TITLE
Move Alex

### PR DESCRIPTION
**Pull request by aaswenson**
Moved myself (finally) to the graduate student section. I broke the picture trend, I don't have a hacker picture!

### CODE REVIEW

**Comment by gonuke** [comment]
Can you put in a head shot for the people page, rather than the landscape with you in the foreground?

**Comment by gonuke** [comment]
since @nuclearkatie got her mods in first, you'll need to rebase against `source` again

**Comment by aaswenson** [comment]
Rebased.

**Comment by pshriwise** [comment]
The image is a little bit colorful compared to the rest, but it'll do. 😄 

LGTM. Thanks @aaswenson

**Comment by gonuke** [comment]
But it's a great!!! idea for the next CNERG images - Union Terrace!

**Comment by pshriwise** [comment]
Agreed!

Looking more closely at that photo... is that photoshopped @aaswenson??

**Pull request merged**
